version: '3.8'
services:
  php:
    build: .
    container_name: php-apache
    ports: 
      - "8081:80"
    depends_on:
      - db
    volumes: 
      - ./:/var/www/html
  db:
    container_name: db
    image: mysql
    restart: always
    volumes:
      - ./dumps:/docker-entrypoint-initdb.d
      - /var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: quiznow
        MYSQL_USER: phpmyadmin
        MYSQL_PASSWORD: 123456
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db